### PR TITLE
feat: Add native gha cache and post-hook support

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

This PR adds native gha cache support so that our users don't need to repeat:

```yaml
- name: Configure sccache
  uses: actions/github-script@v6
  with:
    script: |
      core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
      core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
```

Also this PR adds a post hook which will run `--show-stats`, so users don't need to run `${SCCACHE_PATH} --show-stats` by hand anymore.

image

### CODE REVIEW

**Comment by Xuanwo** [comment]
Let's nice! 

https://github.com/datafuselabs/opendal/actions/runs/3888790374/jobs/6636465132

**Comment by Xuanwo** [comment]
@sylvestre Please take a look~

**Comment by sylvestre** [comment]
Yeah, it is in my todo list. I hope I will get back to you soon on this :)

**Comment by alex** [comment]
does it make sense to also set `RUSTC_WRAPPER`?

**Comment by Xuanwo** [comment]
> does it make sense to also set `RUSTC_WRAPPER`?

I prefer let the user decide.

- User may want to enable sccache explicitly.
- User may use sccache for other language.

**Comment by alex** [comment]
Perhaps an option then? I think this would make it maximally easy for users to adopt sccache.


thanks for your work on this.

**Comment by Xuanwo** [comment]
> Perhaps an option then? I think this would make it maximally easy for users to adopt sccache.

Ok, let's do this in another PR. I think we can provide presets for rust/gcc/clang.

**Pull request merged**
